name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_gitlab_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub repository and GitLab API token
        run: |
          echo "GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}" >> $GITHUB_ENV
          echo "GITLAB_PROJECT_ID=${{ secrets.GITLAB_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
          --form "ref=main" \
          --form "token=${{ secrets.GITLAB_TOKEN }}" \
          "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline"
